language: java

install: mvn -B -U install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn -B verify

jdk:
  - oraclejdk8

notifications:
  email: false

branches:
  only:
    - master
    - /^release.*$/

cache:
  directories:
  - $HOME/.m2
